# ADB
PRODUCT_PROPERTY_OVERRIDES += \
    persist.adb.nonblocking_ffs=0

# AEE
PRODUCT_PROPERTY_OVERRIDES += \
    ro.vendor.aee.convert64=1 \
    ro.vendor.have_aeev_feature=0 \
    ro.vendor.usb.kpoc_adb=0

# Audio
PRODUCT_PROPERTY_OVERRIDES += \
    aaudio.mmap_exclusive_policy=2 \
    aaudio.mmap_policy=2 \
    audio.deep_buffer.media=true \
    audio.offload.min.duration.secs=30 \
    audio.offload.video=true \
    bluetooth.profile.sap.server.enabled=true \
    bluetooth.profile.bap.broadcast.source.enabled=false \
    bluetooth.profile.bap.broadcast.assist.enabled=false \
    bluetooth.profile.bap.unicast.client.enabled=false \
    bluetooth.profile.csip.set_coordinator.enabled=false \
    bluetooth.profile.mcp.server.enabled=false \
    bluetooth.profile.ccp.server.enabled=false \
    bluetooth.profile.vcp.controller.enabled=false \
    persist.bluetooth.a2dp_offload.cap=sbc-aac \
    persist.bluetooth.a2dp_offload.disabled=false \
    persist.vendor.audio.usb.offload=true \
    persist.vendor.debug_policy.ready=1 \
    persist.vendor.debug_policy=minidump \
    persist.vendor.newdirac.cur.config=MUSIC \
    persist.vendor.newdirac.dump=0 \
    persist.vendor.newdirac.enable.value=1.000000 \
    persist.vendor.newdirac.volume.value=0.000000 \
    ro.bluetooth.a2dp_offload.supported=true \
    ro.bluetooth.leaudio_offload.supported=false \
    ro.vendor.mtk_audio_tuning_tool_ver=V1 \
    ro.vendor.mtk_hifiaudio_support=1 \
    ro.audio.spatializer_enabled=true \
    vendor.audio.powerhal.power.dl=true \
    vendor.audio.powerhal.power.ul=true \
    vendor.audio.usb.iems.period_us=5000 \
    persist.vendor.audiohal.aurisys.pcm_dump_on=0 \
    persist.vendor.audiohal.p2w_dump_on=0 \
    persist.vendor.audiohal.pcm_mixer_dump_on=0 \
    vendor.usbsph.dl.pcm.dump=0 \
    vendor.usbsph.ul.pcm.dump=0 \
    vendor.usbsph.srcaws.pcm.dump=0 \
    vendor.streamout.pcm.dump=0 \
    vendor.streamin.pcm.dump=0 \
    vendor.bluetooth.ldac.abr=true

# Bluetooth
PRODUCT_PROPERTY_OVERRIDES += \
    bluetooth.device.default_name=CMF Phone 1 \
    bluetooth.device_id.vendor_id=0x0046 \
    persist.vendor.audio.leaudio_sw_offload=true \
    persist.vendor.bluetooth.leaudio_mode=ums-cg

# Bootloader
PRODUCT_PROPERTY_OVERRIDES += \
    ro.oem_unlock_supported=1

# Camera
PRODUCT_PROPERTY_OVERRIDES += \
    camera.disable_zsl_mode=1 \
    ro.camera.disableJpegR=true \
    ro.camera.disableHeicUltraHDR=true \
    persist.vendor.camera3.pipeline.bufnum.base.imgo=4 \
    persist.vendor.camera3.pipeline.bufnum.base.lcso=4 \
    persist.vendor.camera3.pipeline.bufnum.base.rrzo=4 \
    persist.vendor.camera3.pipeline.bufnum.base.rsso=5 \
    persist.vendor.camera3.pipeline.bufnum.min.high_ram.fdyuv=5 \
    persist.vendor.camera3.pipeline.bufnum.min.high_ram.imgo=7 \
    persist.vendor.camera3.pipeline.bufnum.min.high_ram.lcso=7 \
    persist.vendor.camera3.pipeline.bufnum.min.high_ram.rrzo=6 \
    persist.vendor.camera3.pipeline.bufnum.min.high_ram.rsso=7 \
    persist.vendor.camera3.pipeline.bufnum.min.low_ram.fdyuv=5 \
    persist.vendor.camera3.pipeline.bufnum.min.low_ram.imgo=6 \
    persist.vendor.camera3.pipeline.bufnum.min.low_ram.lcso=6 \
    persist.vendor.camera3.pipeline.bufnum.min.low_ram.rrzo=6 \
    persist.vendor.camera3.pipeline.bufnum.min.low_ram.rsso=6 \
    ro.vendor.camera.directfdyuv.support=1 \
    ro.vendor.camera.insensorzoom.support=1 \
    ro.vendor.camera.isp.support.colorspace=0 \
    ro.vendor.camera3.zsl.default=260 \
    ro.vendor.mtk_backlight_hwc_support=1 \
    ro.vendor.mtk_blulight_def_support=1 \
    ro.vendor.mtk_c2k_lte_mode=0 \
    ro.vendor.mtk_cam_security_support=1 \
    ro.vendor.mtk_camera_app_version=3 \
    vendor.camera.mdp.cz.enable=1 \
    vendor.camera.mdp.dre.enable=1 \
    vendor.mtk.camera.app.fd.video=1 \
    vendor.debug.morpho.videoeis.enable=true \
    vendor.debug.morpho.zoomeis.enable=true \

# Charger
PRODUCT_PROPERTY_OVERRIDES += \
    ro.vendor.mtk_fast_charging_support=1

# Connectivity
PRODUCT_PROPERTY_OVERRIDES += \
    persist.vendor.bluetooth.broadcaster.tx_pwr=10 \
    persist.vendor.bluetooth.connection_improve=yes \
    persist.vendor.bluetooth.supportopphdt=no \
    persist.vendor.connsys.chipid=-1 \
    persist.vendor.connsys.dynamic.dump=0 \
    persist.vendor.connsys.fm_chipid=connac2x \
    persist.vendor.connsys.patch.version=-1 \
    ro.vendor.bt.connac3=no \
    ro.vendor.bt.platform=6878 \
    ro.vendor.connsys.dedicated.log.port=bt,wifi,ics,btmcu,wifimcu \
    ro.vendor.connsys.dedicated.log=1 \
    ro.vendor.fm.platform=connac2x \
    ro.vendor.gps.chrdev=gps_drv_dl_v051 \
    ro.vendor.mtk_agps_app=1 \
    ro.vendor.mtk_gps_support=1 \
    ro.vendor.mtk_log_hide_gps=0 \
    ro.vendor.mtk_wappush_support=1 \
    ro.vendor.mtk_wfd_support=1 \
    ro.vendor.wfd.dummy.enable=0 \
    ro.vendor.wfd.iframesize.level=0 \
    ro.vendor.wifi.sap.concurrent.iface=ap1 \
    ro.vendor.wifi.sap.interface=ap0 \
    ro.vendor.wlan.chrdev=wmt_chrdev_wifi_connac2 \
    ro.vendor.wlan.gen=gen4m_6878 \
    ro.vendor.wlan.standalone.log=y \
    vendor.connsys.driver.ready=no

# Dex2oat64
PRODUCT_PROPERTY_OVERRIDES += \
    dalvik.vm.dex2oat64.enabled=true \
    dalvik.vm.dex2oat-cpu-set=4,5,6,7 \
    dalvik.vm.dex2oat-threads=4 \
    dalvik.vm.image-dex2oat-cpu-set=4,5,6,7 \
    dalvik.vm.image-dex2oat-threads=4

# DRM
PRODUCT_PROPERTY_OVERRIDES += \
    drm.service.enabled=true \
    ro.vendor.mtk_config_max_dram_size= \
    ro.vendor.mtk_widevine_drm_l1_support=1

# EGL
PRODUCT_PROPERTY_OVERRIDES += \
    ro.vendor.arm.egl.configs.nv12.hal_format=0x200 \
    ro.vendor.arm.egl.configs.nv12.recordable=true \
    ro.vendor.arm.egl.configs.nv16.hal_format=0x10 \
    ro.vendor.arm.egl.configs.nv16.recordable=true \
    ro.vendor.arm.egl.configs.nv21.hal_format=0x201 \
    ro.vendor.arm.egl.configs.nv21.recordable=true \
    ro.vendor.arm.egl.configs.p010.hal_format=0x204 \
    ro.vendor.arm.egl.configs.p010.recordable=true \
    ro.vendor.arm.egl.configs.p210.hal_format=0x205 \
    ro.vendor.arm.egl.configs.p210.recordable=true \
    ro.vendor.arm.egl.configs.r10_g10_b10_a2_32bit_fixed.framebuffer_target=false \
    ro.vendor.arm.egl.configs.r10_g10_b10_a2_32bit_fixed.hal_format=0x2b \
    ro.vendor.arm.egl.configs.r10_g10_b10_a2_32bit_fixed.recordable=false \
    ro.vendor.arm.egl.configs.r16_g16_b16_a16_64bit_float.framebuffer_target=false \
    ro.vendor.arm.egl.configs.r16_g16_b16_a16_64bit_float.hal_format=0x16 \
    ro.vendor.arm.egl.configs.r16_g16_b16_a16_64bit_float.recordable=false \
    ro.vendor.arm.egl.configs.r5_g6_b5_a0_16bit_fixed.framebuffer_target=false \
    ro.vendor.arm.egl.configs.r5_g6_b5_a0_16bit_fixed.hal_format=0x4 \
    ro.vendor.arm.egl.configs.r5_g6_b5_a0_16bit_fixed.recordable=false \
    ro.vendor.arm.egl.configs.r8_g8_b8_a0_24bit_fixed.framebuffer_target=false \
    ro.vendor.arm.egl.configs.r8_g8_b8_a0_24bit_fixed.hal_format=0x2 \
    ro.vendor.arm.egl.configs.r8_g8_b8_a0_24bit_fixed.recordable=false \
    ro.vendor.arm.egl.configs.r8_g8_b8_a0_24bit_yuv_special.framebuffer_target=false \
    ro.vendor.arm.egl.configs.r8_g8_b8_a0_24bit_yuv_special.hal_format=0x23 \
    ro.vendor.arm.egl.configs.r8_g8_b8_a0_32bit_fixed.framebuffer_target=false \
    ro.vendor.arm.egl.configs.r8_g8_b8_a0_32bit_fixed.hal_format=0x2 \
    ro.vendor.arm.egl.configs.r8_g8_b8_a0_32bit_fixed.recordable=false \
    ro.vendor.arm.egl.configs.r8_g8_b8_a8_32bit_fixed.framebuffer_target=false \
    ro.vendor.arm.egl.configs.r8_g8_b8_a8_32bit_fixed.hal_format=0x1 \
    ro.vendor.arm.egl.configs.r8_g8_b8_a8_32bit_fixed.recordable=true \
    ro.vendor.arm.egl.configs.y0l2.hal_format=0x203 \
    ro.vendor.arm.egl.configs.y0l2.recordable=true \
    ro.vendor.arm.egl.configs.y210.hal_format=0x206 \
    ro.vendor.arm.egl.configs.y210.recordable=true \
    ro.vendor.arm.egl.configs.y410.hal_format=0x207 \
    ro.vendor.arm.egl.configs.y410.recordable=true \
    ro.vendor.arm.egl.configs.yuv420.hal_format=0x208 \
    ro.vendor.arm.egl.configs.yuv420.recordable=true \
    ro.vendor.arm.egl.configs.yuyv.hal_format=0x202 \
    ro.vendor.arm.egl.configs.yuyv.recordable=true \
    ro.vendor.arm.egl.configs.yvu420.hal_format=0x20e \
    ro.vendor.arm.egl.configs.yvu420.recordable=true \
    ro.vendor.arm.gralloc.afrc_chroma_usage_flags=0x100000000000000,0x80000000000000,0x180000000000000 \
    ro.vendor.arm.gralloc.afrc_chroma_usage_mask=0x180000000000000 \
    ro.vendor.arm.gralloc.afrc_luma_usage_flags=0x50000000,0x60000000,0x40000000 \
    ro.vendor.arm.gralloc.afrc_luma_usage_mask=0x70000000 \
    ro.vendor.arm.gralloc.afrc_rgba_usage_flags=0x50000000,0x60000000,0x40000000 \
    ro.vendor.arm.gralloc.afrc_rgba_usage_mask=0x70000000 \
    ro.vendor.arm.gralloc.force_back_buffer_usage_flags=0x40000000000000 \
    ro.vendor.arm.gralloc.force_back_buffer_usage_mask=0x40000000000000 \
    ro.vendor.arm.gralloc.no_afbc_usage_flags=0x200000000000000 \
    ro.vendor.arm.gralloc.no_afbc_usage_mask=0x1200000000000000 \
    ro.vendor.arm.gralloc.shared_access_usage_flags=0x10000000 \
    ro.vendor.arm.gralloc.shared_access_usage_mask=0x50000000

# FS
PRODUCT_PROPERTY_OVERRIDES += \
    ro.incremental.enable=yes \
    ro.vendor.mtk_emmc_support=1 \
    ro.vendor.mtk_f2fs_enable=1 \
    ro.vendor.mtk_fd_support=1

# Graphics
PRODUCT_PROPERTY_OVERRIDES += \
    debug.graphics.game_default_frame_rate.disabled=true \
    debug.sf.auto_latch_unsignaled=1 \
    debug.sf.early.app.duration.120=11600000 \
    debug.sf.early.app.duration.90=16600000 \
    debug.sf.early.app.duration.60=16600000 \
    debug.sf.early.app.duration=18000000 \
    debug.sf.early.sf.duration.120=12300000 \
    debug.sf.early.sf.duration.90=16100000 \
    debug.sf.early.sf.duration.60=15600000 \
    debug.sf.early.sf.duration=14600000 \
    debug.sf.earlyGl.app.duration.120=11600000 \
    debug.sf.earlyGl.app.duration.90=16600000 \
    debug.sf.earlyGl.app.duration.60=16600000 \
    debug.sf.earlyGl.app.duration=18000000 \
    debug.sf.earlyGl.sf.duration.120=12300000 \
    debug.sf.earlyGl.sf.duration.90=16100000 \
    debug.sf.earlyGl.sf.duration.60=15600000 \
    debug.sf.earlyGl.sf.duration=14600000 \
    debug.sf.enable_adpf_cpu_hint=true \
    debug.sf.enable_gl_backpressure=0 \
    debug.sf.enable_hwc_vds=0 \
    debug.sf.enable_transaction_tracing=false \
    debug.sf.hwc.min.duration=2000000 \
    debug.sf.late.app.duration.120=11600000 \
    debug.sf.late.app.duration.90=16600000 \
    debug.sf.late.app.duration.60=16600000 \
    debug.sf.late.app.duration=18000000 \
    debug.sf.late.sf.duration.120=12300000 \
    debug.sf.late.sf.duration.90=16100000 \
    debug.sf.late.sf.duration.60=15600000 \
    debug.sf.late.sf.duration=14600000 \
    debug.sf.predict_hwc_composition_strategy=0 \
    debug.sf.set_binder_thread_rt=1 \
    debug.sf.use_phase_offsets_as_durations=1 \
    debug.renderengine.backend=skiaglthreaded \
    debug.stagefright.c2inputsurface=-1 \
    graphics.gpu.profiler.support=true \
    persist.sys.sf.native_mode=260 \
    ro.gfx.driver.0=com.mediatek.mt6878.gamedriver \
    ro.hardware.egl=mali \
    ro.hardware.gralloc=common \
    ro.hardware.hwcomposer=mtk_common \
    ro.hardware.vulkan=mali \
    ro.opengles.version=196610 \
    ro.sf.blurs_are_expensive=1 \
    ro.surface_flinger.force_hwc_copy_for_virtual_displays=true \
    ro.surface_flinger.has_HDR_display=true \
    ro.surface_flinger.has_wide_color_display=true \
    ro.surface_flinger.max_frame_buffer_acquired_buffers=4 \
    ro.surface_flinger.primary_display_orientation=ORIENTATION_0 \
    ro.surface_flinger.protected_contents=true \
    ro.surface_flinger.set_idle_timer_ms=3000 \
    ro.surface_flinger.set_touch_timer_ms=500 \
    ro.surface_flinger.uclamp.min=328 \
    ro.surface_flinger.use_color_management=true \
    ro.surface_flinger.use_content_detection_for_refresh_rate=true \
    ro.surface_flinger.wcg_composition_dataspace=143261696 \
    ro.vendor.arm.egl.configs.nv12.hal_format=0x200 \
    ro.vendor.arm.egl.configs.nv12.recordable=true \
    ro.vendor.arm.egl.configs.nv16.hal_format=0x10 \
    ro.vendor.arm.egl.configs.nv16.recordable=true \
    ro.vendor.arm.egl.configs.nv21.hal_format=0x201 \
    ro.vendor.arm.egl.configs.nv21.recordable=true \
    ro.vendor.arm.egl.configs.p010.hal_format=0x204 \
    ro.vendor.arm.egl.configs.p010.recordable=true \
    ro.vendor.arm.egl.configs.p210.hal_format=0x205 \
    ro.vendor.arm.egl.configs.p210.recordable=true \
    ro.vendor.arm.egl.configs.r10_g10_b10_a2_32bit_fixed.framebuffer_target=false \
    ro.vendor.arm.egl.configs.r10_g10_b10_a2_32bit_fixed.hal_format=0x2b \
    ro.vendor.arm.egl.configs.r10_g10_b10_a2_32bit_fixed.recordable=false \
    ro.vendor.arm.egl.configs.r16_g16_b16_a16_64bit_float.framebuffer_target=false \
    ro.vendor.arm.egl.configs.r16_g16_b16_a16_64bit_float.hal_format=0x16 \
    ro.vendor.arm.egl.configs.r16_g16_b16_a16_64bit_float.recordable=false \
    ro.vendor.arm.egl.configs.r5_g6_b5_a0_16bit_fixed.framebuffer_target=false \
    ro.vendor.arm.egl.configs.r5_g6_b5_a0_16bit_fixed.hal_format=0x4 \
    ro.vendor.arm.egl.configs.r5_g6_b5_a0_16bit_fixed.recordable=false \
    ro.vendor.arm.egl.configs.r8_g8_b8_a0_24bit_fixed.framebuffer_target=false \
    ro.vendor.arm.egl.configs.r8_g8_b8_a0_24bit_fixed.hal_format=0x2 \
    ro.vendor.arm.egl.configs.r8_g8_b8_a0_24bit_fixed.recordable=false \
    ro.vendor.arm.egl.configs.r8_g8_b8_a0_24bit_yuv_special.framebuffer_target=false \
    ro.vendor.arm.egl.configs.r8_g8_b8_a0_24bit_yuv_special.hal_format=0x23 \
    ro.vendor.arm.egl.configs.r8_g8_b8_a0_32bit_fixed.framebuffer_target=false \
    ro.vendor.arm.egl.configs.r8_g8_b8_a0_32bit_fixed.hal_format=0x2 \
    ro.vendor.arm.egl.configs.r8_g8_b8_a0_32bit_fixed.recordable=false \
    ro.vendor.arm.egl.configs.r8_g8_b8_a8_32bit_fixed.framebuffer_target=false \
    ro.vendor.arm.egl.configs.r8_g8_b8_a8_32bit_fixed.hal_format=0x1 \
    ro.vendor.arm.egl.configs.r8_g8_b8_a8_32bit_fixed.recordable=true \
    ro.vendor.arm.egl.configs.y0l2.hal_format=0x203 \
    ro.vendor.arm.egl.configs.y0l2.recordable=true \
    ro.vendor.arm.egl.configs.y210.hal_format=0x206 \
    ro.vendor.arm.egl.configs.y210.recordable=true \
    ro.vendor.arm.egl.configs.y410.hal_format=0x207 \
    ro.vendor.arm.egl.configs.y410.recordable=true \
    ro.vendor.arm.egl.configs.yuv420.hal_format=0x208 \
    ro.vendor.arm.egl.configs.yuv420.recordable=true \
    ro.vendor.arm.egl.configs.yuyv.hal_format=0x202 \
    ro.vendor.arm.egl.configs.yuyv.recordable=true \
    ro.vendor.arm.egl.configs.yvu420.hal_format=0x20e \
    ro.vendor.arm.egl.configs.yvu420.recordable=true \
    ro.vendor.arm.gralloc.afrc_chroma_usage_flags=0x100000000000000,0x80000000000000,0x180000000000000 \
    ro.vendor.arm.gralloc.afrc_chroma_usage_mask=0x180000000000000 \
    ro.vendor.arm.gralloc.afrc_luma_usage_flags=0x50000000,0x60000000,0x40000000 \
    ro.vendor.arm.gralloc.afrc_luma_usage_mask=0x70000000 \
    ro.vendor.arm.gralloc.afrc_rgba_usage_flags=0x50000000,0x60000000,0x40000000 \
    ro.vendor.arm.gralloc.afrc_rgba_usage_mask=0x70000000 \
    ro.vendor.arm.gralloc.force_back_buffer_usage_flags=0x40000000000000 \
    ro.vendor.arm.gralloc.force_back_buffer_usage_mask=0x40000000000000 \
    ro.vendor.arm.gralloc.no_afbc_usage_flags=0x200000000000000 \
    ro.vendor.arm.gralloc.no_afbc_usage_mask=0x1200000000000000 \
    ro.vendor.arm.gralloc.shared_access_usage_flags=0x10000000 \
    ro.vendor.arm.gralloc.shared_access_usage_mask=0x50000000 \
    ro.vendor.composer_version=3.2 \
    ro.vendor.display.array.auto.backlight=28,28,53,135,275,335,364,473,560,616,740,878,1036,1304,1406,2047,2047,2680,3115,4090 \
    ro.vendor.display.array.auto.lux=0,1,4,10,25,60,150,390,620,750,1000,1300,1700,2800,3500,4500,7000,8000,20000,40000 \
    ro.vendor.display.array.auto.nits=7,7,14,34,70,84,90,111,132,145,178,211,248,318,344,500,500,700,850,1000 \
    ro.vendor.display.array.backlight=28,28,53,135,275,335,364,473,560,616,740,878,1036,1304,1406,2047,2047,2680 \
    ro.vendor.display.array.hbm.backlight=2680,3115,4090 \
    ro.vendor.display.array.hbm.maxlux=8000,20000,40000 \
    ro.vendor.display.array.hbm.minlux=7000,18000,38000 \
    ro.vendor.display.array.lux=0,1,4,10,25,60,150,390,620,750,1000,1300,1700,2800,3500,4500,7000,8000 \
    ro.vendor.display.array.nits=7,7,14,34,70,84,90,111,132,145,178,211,248,318,344,500,500,700 \
    ro.vendor.display.hbm.maxbacklight=4095 \
    ro.vendor.display.low_brightness_threshold=0.108 \
    ro.vendor.display.normal.maxbacklight=2680 \
    ro.vendor.display.normal.minbacklight=4 \
    ro.vendor.display.panel.type=AMOLED \
    ro.vendor.display.safe.backlight=2047 \
    ro.vendor.display.set_doze_fps_modeid=0 \
    ro.vendor.display.set_hdr_brightness_early=1 \
    ro.vendor.display.thermal_limit_brightness=4095,3543,2974,2680,2047,1806,1635,1433,1248,1046,832 \
    ro.vendor.display.user.control.lux=0,100,1000,2500,4500 \
    vendor.display.enable_ic_hw_roundedcorner=1 \
    vendor.debug.sf.cpupolicy.base_min_bl=298 \
    vendor.debug.sf.cpupolicy.bl_mask=240 \
    vendor.debug.sf.cpupolicy.dp.base_min_bl=489 \
    vendor.debug.sf.cpupolicy.dp.upbound_uclamp_min=683 \
    vendor.debug.sf.cpupolicy.foreground=1 \
    vendor.debug.sf.cpupolicy.hw_comp_suspend=1 \
    vendor.debug.sf.cpupolicy.ll_mask=15 \
    vendor.debug.sf.cpupolicy.llbl_mask=255 \
    vendor.debug.sf.cpupolicy.lowbound_uclamp_min=113 \
    vendor.debug.sf.cpupolicy.max_correct_offset=194 \
    vendor.debug.sf.cpupolicy.min_120=110 \
    vendor.debug.sf.cpupolicy.min_144=110 \
    vendor.debug.sf.cpupolicy.min_30_mml=80 \
    vendor.debug.sf.cpupolicy.min_60=76 \
    vendor.debug.sf.cpupolicy.min_60_mml=80 \
    vendor.debug.sf.cpupolicy.min_90=110 \
    vendor.debug.sf.cpupolicy.min_boost=110 \
    vendor.debug.sf.cpupolicy.power_down_120=600000 \
    vendor.debug.sf.cpupolicy.power_up_120=-600000 \
    vendor.debug.sf.cpupolicy.re_hfr=1 \
    vendor.debug.sf.cpupolicy.rt_bl_min=274 \
    vendor.debug.sf.cpupolicy.sf_cpu_thres=194 \
    vendor.debug.sf.cpupolicy.sus_correct_max=25 \
    vendor.debug.sf.cpupolicy.sus_correct_min=-15 \
    vendor.debug.sf.cpupolicy.upbound_uclamp_max_ll=182 \
    vendor.debug.sf.cpupolicy.upbound_uclamp_min=409 \
    vendor.debug.sf.cpupolicy.upbound_uclamp_ret_sys=144 \
    vendor.debug.sf.cpupolicy.xgf_min=25 \
    vendor.debug.sf.dynamic_duration.app.decouple=20000000 \
    vendor.debug.sf.dynamic_duration.app.early=18000000 \
    vendor.debug.sf.dynamic_duration.app.early.120=11600000 \
    vendor.debug.sf.dynamic_duration.app.early.60=16600000 \
    vendor.debug.sf.dynamic_duration.app.early.90=14600000 \
    vendor.debug.sf.dynamic_duration.app.earlyGl=18000000 \
    vendor.debug.sf.dynamic_duration.app.earlyGl.120=11600000 \
    vendor.debug.sf.dynamic_duration.app.earlyGl.60=16600000 \
    vendor.debug.sf.dynamic_duration.app.earlyGl.90=14600000 \
    vendor.debug.sf.dynamic_duration.app.late=18000000 \
    vendor.debug.sf.dynamic_duration.app.late.120=11600000 \
    vendor.debug.sf.dynamic_duration.app.late.60=16600000 \
    vendor.debug.sf.dynamic_duration.app.late.90=14600000 \
    vendor.debug.sf.dynamic_duration.sf.decouple=27600000 \
    vendor.debug.sf.dynamic_duration.sf.early=14600000 \
    vendor.debug.sf.dynamic_duration.sf.early.120=12300000 \
    vendor.debug.sf.dynamic_duration.sf.early.60=15600000 \
    vendor.debug.sf.dynamic_duration.sf.early.90=13100000 \
    vendor.debug.sf.dynamic_duration.sf.earlyGl=14600000 \
    vendor.debug.sf.dynamic_duration.sf.earlyGl.120=12300000 \
    vendor.debug.sf.dynamic_duration.sf.earlyGl.60=15600000 \
    vendor.debug.sf.dynamic_duration.sf.earlyGl.90=13100000 \
    vendor.debug.sf.dynamic_duration.sf.late=14600000 \
    vendor.debug.sf.dynamic_duration.sf.late.120=12300000 \
    vendor.debug.sf.dynamic_duration.sf.late.60=15600000 \
    vendor.debug.sf.dynamic_duration.sf.late.90=13100000 \
    vendor.debug.sf.dynamic_duration.switch=1 \
    vendor.debug.sf.fbthint=1

# HWUI
PRODUCT_PROPERTY_OVERRIDES += \
debug.hwui.target_cpu_time_percent=30 \
debug.hwui.use_hint_manager=true

# Keymint
PRODUCT_PROPERTY_OVERRIDES += \
    ro.apk_verity.mode=1 \
    ro.crypto.volume.filenames_mode=aes-256-cts \
    ro.hardware.gatekeeper=trustonic \
    ro.hardware.kmsetkey=trustonic \
    ro.mtk_key_manager_support=1 \
    ro.vendor.mtk_tee_gp_support=1 \
    ro.vendor.mtk_trustonic_tee_support=1

# LMK
PRODUCT_PROPERTY_OVERRIDES += \
    ro.lmk.downgrade_pressure=60 \
    ro.lmk.filecache_min_kb=153600 \
    ro.lmk.kill_timeout_ms=100 \
    ro.lmk.stall_limit_critical=40 \
    ro.lmk.psi_complete_stall_ms=700 \
    ro.lmk.swap_free_low_percentage=10 \
    ro.lmk.swap_util_max=90 \
    ro.lmk.thrashing_limit=40 \
    ro.lmk.thrashing_limit_decay=10 \
    ro.logd.kernel=false

# Media
PRODUCT_PROPERTY_OVERRIDES += \
    media.c2.dmabuf.padding=3072 \
    media.stagefright.thumbnail.prefer_hw_codecs=true \
    ro.vendor.jpeg_decode_sw_opt=1 \
    ro.vendor.mtk.c2.vdec.fmt.support.level=3 \
    ro.vendor.mtk.c2.vdec.vpp.turnkey.memc=1 \
    ro.vendor.mtk.gpud.mm.fbc.disable=false \
    ro.vendor.mtk_aod_support=1 \
    ro.vendor.mtk_hdr_video_support=1 \
    ro.vendor.mtk_video_hevc_enc_support=1 \
    vendor.mtk.vdec.decode.error.handle.mode=1 \
    vendor.mtk.vdec.waitkeyframeforplay=9 \
    vendor.mtk_thumbnail_optimization=true \
    vendor.performance.frs.tz_name=shell_max \
    vendor.video.framework.thumbnail.SurfaceMode=1

# MTK
PRODUCT_PROPERTY_OVERRIDES += \
    ro.vendor.mediatek.platform=MT6878 \
    ro.vendor.mediatek.version.branch=alps-mp-u0.mp1 \
    ro.vendor.mediatek.version.release=alps-mp-u0.mp1.rc-V6.4_nothing.u0mp1rc.k6989v1.64_P1 \
    ro.vendor.mgk_name=mgk_64_k61 \
    ro.vendor.mgvi_name=mgvi_64_64only_ww_armv82 \
    ro.vendor.mml.mtk_mml_support=1

# Netflix
PRODUCT_PROPERTY_OVERRIDES += \
    ro.netflix.bsp_rev=MT6878-38373-1

# NNAPI
PRODUCT_PROPERTY_OVERRIDES += \
    debug.mtk_tflite.target_nnapi=29 \
    ro.vendor.mtk_nn.option=A,B,C,D,E,F,G,Z \
    ro.vendor.mtk_nn_baseline_support=1 \
    ro.vendor.mtk_nn_quant_preferred=1 \
    ro.vendor.mtk_nn_support=1 \
    ro.vendor.mtk_ovl_bringup=0

# Nothing
PRODUCT_PROPERTY_OVERRIDES += \
    ro.vendor.nothing.feature.base=0x28124a040124b4247b97ffL \
    ro.vendor.nothing.feature.diff.device.Pacman=0x890493f4d20258c42080L \
    ro.vendor.nothing.feature.diff.device.PacmanPro=0x289b493f4d20258c42080L \
    ro.vendor.nothing.feature.diff.device.Pong=0x20044a404803d1842000L \
    ro.vendor.nothing.feature.diff.device.Spacewar=0x20042a0041a032c34000L \
    ro.vendor.nothing.feature.diff.device.Tetris=0x2cf3b13f4f22258c401c0L \
    ro.vendor.nothing.feature.diff.product.Pong=0x0 \
    ro.vendor.nothing.feature.diff.product.PongEEA=0x0 \
    ro.vendor.nothing.feature.diff.product.PongIND=0x0 \
    ro.vendor.nothing.feature.diff.product.Spacewar=0x0 \
    ro.vendor.nothing.feature.diff.product.SpacewarEEA=0x0

# PQ
PRODUCT_PROPERTY_OVERRIDES += \
    debug.mediatek.appgamepq_compress=1 \
    debug.mediatek.disp_decompress=1 \
    persist.vendor.sys.pq.disp.ccorr.silky.brightness=0 \
    persist.vendor.sys.pq.disp.gamma.silky.brightness=0 \
    persist.vendor.sys.pq.disp_gamma_silky_brightness_by_hwc=0 \
    persist.vendor.sys.pq.mtk_disp_clarity_support=0 \
    ro.vendor.mtk_pq_color_mode=1 \
    ro.vendor.mtk_pq_support=2 \
    ro.vendor.mtk_prefer_64bit_proc=1 \
    ro.vendor.pq.mtk_aal_support=0 \
    ro.vendor.pq.mtk_ai_hdr_model_dq=0 \
    ro.vendor.pq.mtk_ai_region_pq_support=0 \
    ro.vendor.pq.mtk_ai_scence_pq_support=0 \
    ro.vendor.pq.mtk_ai_sdr_to_hdr_support=0 \
    ro.vendor.pq.mtk_backlight_smooth_support=0 \
    ro.vendor.pq.mtk_blulight_def_support=1 \
    ro.vendor.pq.mtk_caltm_support=0 \
    ro.vendor.pq.mtk_clearzoom_support=0 \
    ro.vendor.pq.mtk_dc_support=0 \
    ro.vendor.pq.mtk_disp_c3d_support=1 \
    ro.vendor.pq.mtk_disp_ccorr_support=1 \
    ro.vendor.pq.mtk_disp_color_support=1 \
    ro.vendor.pq.mtk_disp_game_pq_support=0 \
    ro.vendor.pq.mtk_disp_gamma_support=1 \
    ro.vendor.pq.mtk_disp_tdshp_support=0 \
    ro.vendor.pq.mtk_dre30_support=0 \
    ro.vendor.pq.mtk_dre_cap=0 \
    ro.vendor.pq.mtk_ds_support=0 \
    ro.vendor.pq.mtk_hdr10_panel_dtmo_support=0 \
    ro.vendor.pq.mtk_hdr10_plus_recording_support=0 \
    ro.vendor.pq.mtk_hfg_support=0 \
    ro.vendor.pq.mtk_libaibld_name=libaibld.nn6.so \
    ro.vendor.pq.mtk_mdp_ccorr_support=0 \
    ro.vendor.pq.mtk_mdp_lite_pq_support=0 \
    ro.vendor.pq.mtk_mml_c3d_support=0 \
    ro.vendor.pq.mtk_mmlpq_support=1 \
    ro.vendor.pq.mtk_pq_interface_support=0 \
    ro.vendor.pq.mtk_pq_video_whitelist_support=0 \
    ro.vendor.pq.mtk_scltm_support=0 \
    ro.vendor.pq.mtk_silky_brigtness_support=0 \
    ro.vendor.pq.mtk_ultra_dimming_support=0 \
    ro.vendor.pq.mtk_ultra_resolution_support=0 \
    ro.vendor.pq.mtk_video_transition=0 \
    ro.vendor.pref_scale_enable_cfg=1

# Radio
PRODUCT_PROPERTY_OVERRIDES += \
    persist.radio.multisim.config=dsds \
    persist.vendor.factory.GB2312=yes \
    persist.vendor.ims_support=1 \
    persist.vendor.log.tel_log_ctrl=1 \
    persist.vendor.md_c2k_cap_dep_check=0 \
    persist.vendor.mims_support=2 \
    persist.vendor.mtk.aee.explevel=4 \
    persist.vendor.mtk.volte.enable=1 \
    persist.vendor.mtk_ct_volte_support=3 \
    persist.vendor.mtk_dynamic_ims_switch=1 \
    persist.vendor.mtk_sim_switch_policy=2 \
    persist.vendor.mtk_wfc_support=1 \
    persist.vendor.radio.msimmode=dsds \
    persist.vendor.radio.mtk_dsbp_support=3 \
    persist.vendor.radio.mtk_ps2_rat=N/L/W/G \
    persist.vendor.radio.mtk_ps3_rat=G \
    persist.vendor.radio.nr_display_rule=0 \
    persist.vendor.radio.smart.data.switch=1 \
    persist.vendor.speech.usb.offload=true \
    persist.vendor.vilte_support=1 \
    persist.vendor.viwifi_support=1 \
    persist.vendor.volte_support=1 \
    persist.vendor.vt.camera.rotate=1 \
    persist.vendor.wfc.cnop_vowifi=1 \
    ro.telephony.default_network=32,32,32,32 \
    ro.telephony.iwlan_operation_mode=AP-assisted \
    ro.telephony.sim.count=2 \
    ro.vendor.afbc.enable=3 \
    ro.vendor.ap_info_monitor=0 \
    ro.vendor.md_auto_setup_ims=1 \
    ro.vendor.md_log_memdump_wait=15 \
    ro.vendor.md_prop_ver=1 \
    ro.vendor.mtk_data_config=1 \
    ro.vendor.mtk_eccci_c2k=1 \
    ro.vendor.mtk_external_sim_only_slots=0 \
    ro.vendor.mtk_lte_support=1 \
    ro.vendor.mtk_mcf_support=1 \
    ro.vendor.mtk_md_world_mode_support=1 \
    ro.vendor.mtk_mipc_support=1 \
    ro.vendor.mtk_mobile_management=1 \
    ro.vendor.mtk_modem_monitor_support=1 \
    ro.vendor.mtk_mvpu_security_support=0 \
    ro.vendor.mtk_mvpu_support=0 \
    ro.vendor.mtk_protocol1_rat_config=N/Lf/Lt/W/G \
    ro.vendor.mtk_ps1_rat=N/Lf/Lt/W/G \
    ro.vendor.mtk_ril_mode=c6m_1rild \
    ro.vendor.mtk_rild_read_imsi=1 \
    ro.vendor.mtk_sec_video_path_support=1 \
    ro.vendor.mtk_sim_card_onoff=3 \
    ro.vendor.mtk_sim_hot_swap_common_slot=1 \
    ro.vendor.mtk_single_bin_modem_support=1 \
    ro.vendor.mtk_thin_md_telephony_support_mode=0 \
    ro.vendor.mtk_world_phone_policy=0 \
    ro.vendor.num_md_protocol=2 \
    ro.vendor.radio.max.multisim=dsds \
    ro.vendor.ril.set_sbp_place=0 \
    ro.vendor.sim_me_lock_mode=3 \
    ro.vendor.vt.mtk_thin_md_support_mode=0 \
    ro.vendor.vt_hevc_support=1 \
    telephony.active_modems.max_count=2

# Surfacelinger
PRODUCT_PROPERTY_OVERRIDES += \
    debug.sf.enable_egl_image_tracker=0

# Sensor
PRODUCT_PROPERTY_OVERRIDES += \
    ro.vendor.init.sensor.rc=init.sensor_2_0.rc \
    ro.vendor.mtk.sensor.support=yes \
    ro.vendor.mtk_thermal_2_0=1

# Vendor logtag
PRODUCT_PROPERTY_OVERRIDES += \
    persist.log.tag.AT=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.AdnRecord=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.AdnRecordCache=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.AdnRecordLoader=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.AirplaneHandler=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.CapaSwitch=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.CarrierExpressServiceImpl=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.CarrierExpressServiceImplExt=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.CountryDetector=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.DSSelector=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.DSSelectorOP01=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.DSSelectorOP02=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.DSSelectorOP09=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.DSSelectorOP18=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.DSSelectorOm=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.DSSelectorUtil=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.DataDispatcher=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.ExternalSimMgr=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.GsmCallTkrHlpr=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.GsmCdmaConn=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.GsmCdmaPhone=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.IMSRILRequest=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.IMS_RILA=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.IccCardProxy=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.IccPhoneBookIM=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.IccProvider=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.ImsApp=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.ImsBaseCommands=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.ImsCall=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.ImsCallProfile=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.ImsCallSession=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.ImsEcbm=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.ImsEcbmProxy=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.ImsManager=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.ImsPhone=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.ImsPhoneBase=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.ImsPhoneCall=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.ImsService=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.ImsVTProvider=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.InterfaceManager=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.IsimFileHandler=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.IsimRecords=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.MTKSST=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.MTK_APPList=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.MipcEventHandler=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.MtkAdnRecord=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.MtkCsimFH=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.MtkEmbmsAdaptor=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.MtkFactory=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.MtkGsmCdmaConn=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.MtkIccCardProxy=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.MtkIccPHBIM=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.MtkIccProvider=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.MtkIccSmsInterfaceManager=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.MtkImsManager=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.MtkImsService=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.MtkIsimFH=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.MtkPhoneNotifr=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.MtkPhoneNumberUtils=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.MtkPhoneSwitcher=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.MtkRecordLoader=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.MtkRuimFH=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.MtkSIMFH=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.MtkSIMRecords=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.MtkSmsCbHeader=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.MtkSmsManager=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.MtkSmsMessage=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.MtkSpnOverride=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.MtkSubCtrl=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.MtkTelephonyManagerEx=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.MtkUiccCard=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.MtkUiccCardApp=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.MtkUiccCtrl=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.MtkUsimFH=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.MtkUsimPhoneBookManager=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.MwiRIL=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.NetAgentService=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.NetAgent_IO=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.NetLnkEventHdlr=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.NetworkPolicy=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.NetworkStats=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.OperatorUtils=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.PQ_DS=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.Phone=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.PhoneConfigurationSettings=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.PhoneFactory=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.PowerHalAddressUitls=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.PowerHalMgrImpl=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.PowerHalMgrServiceImpl=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.PowerHalWifiMonitor=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.ProxyController=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.RFX=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.RIL-Fusion=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.RIL-Netlink=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.RIL-Parcel=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.RIL-SocListen=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.RIL-Socket=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.RIL=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.RILC-OP=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.RILC=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.RILD=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.RILMD2-SS=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.RIL_UIM_SOCKET=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.RadioManager=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.RfxAction=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.RfxBaseHandler=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.RfxChannelMgr=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.RfxCloneMgr=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.RfxContFactory=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.RfxController=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.RfxDebugInfo=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.RfxDisThread=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.RfxFragEnc=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.RfxHandlerMgr=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.RfxIdToMsgId=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.RfxIdToStr=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.RfxMainThread=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.RfxMclDisThread=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.RfxMclMessenger=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.RfxMclStatusMgr=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.RfxMessage=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.RfxObject=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.RfxOpUtils=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.RfxRilAdapter=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.RfxRilUtils=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.RfxRoot=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.RfxStatusMgr=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.RfxTimer=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.RilClient=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.RilOemClient=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.RilOpProxy=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.RmmCapa=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.RmmCommSimOpReq=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.RmmDcEvent=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.RmmDcPdnManager=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.RmmDcUrcHandler=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.RmmDcUtility=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.RmmDch=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.RmmDchUrc=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.RmmEccNumberReqHdlr=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.RmmEccNumberUrcHandler=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.RmmEmbmsReq=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.RmmEmbmsUrc=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.RmmImsCtlReqHdl=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.RmmImsCtlUrcHdl=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.RmmMwi=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.RmmNwAsyncHdlr=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.RmmNwHdlr=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.RmmNwNrtReqHdlr=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.RmmNwRTReqHdlr=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.RmmNwRatSwHdlr=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.RmmNwReqHdlr=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.RmmNwUrcHdlr=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.RmmOemHandler=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.RmmOpRadioReq=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.RmmPhbReq=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.RmmPhbUrc=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.RmmRadioReq=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.RmmSimBaseHandler=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.RmmSimCommReq=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.RmmSimCommUrc=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.RmmWp=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.RtmCapa=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.RtmCommSimCtrl=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.RtmDC=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.RtmEccNumberController=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.RtmEmbmsAt=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.RtmEmbmsUtil=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.RtmIms=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.RtmImsConference=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.RtmImsConfigController=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.RtmImsDialog=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.RtmModeCont=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.RtmMwi=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.RtmNwCtrl=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.RtmPhb=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.RtmRadioConfig=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.RtmRadioCont=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.RtmWp=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.SIMRecords=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.SimSwitchOP01=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.SimSwitchOP02=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.SimSwitchOP18=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.SlotQueueEntry=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.SpnOverride=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.UiccCard=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.UiccController=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.UxUtility=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.VT=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.VsimAdaptor=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.WORLDMODE=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.WfoApp=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.WpfaCcciDataHeaderEncoder=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.WpfaCcciReader=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.WpfaCcciSender=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.WpfaControlMsgHandler=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.WpfaDriver=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.WpfaDriverAccept=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.WpfaDriverAdapter=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.WpfaDriverDeReg=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.WpfaDriverMessage=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.WpfaDriverRegFilter=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.WpfaDriverULIpPkt=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.WpfaDriverUtilis=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.WpfaDriverVersion=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.WpfaFilterRuleReqHandler=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.WpfaParsing=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.WpfaRingBuffer=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.WpfaRuleContainer=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.WpfaRuleRegister=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.WpfaShmAccessController=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.WpfaShmReadMsgHandler=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.WpfaShmSynchronizer=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.WpfaShmWriteMsgHandler=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.libPowerHal=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.mipc_lib=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.mtkpower@impl=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.mtkpower_client=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.trm_lib=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.wpfa_iptable_android=$(VENDOR_LOG_LEVEL)

# RKPD
PRODUCT_PROPERTY_OVERRIDES += \
    remote_provisioning.enable_rkpd=true \
    remote_provisioning.hostname=remoteprovisioning.googleapis.com \
    remote_provisioning.connect_timeout_millis=2000
    
# ZRAM
PRODUCT_PROPERTY_OVERRIDES += \
ro.zram.mark_idle_delay_mins=60 \
ro.zram.first_wb_delay_mins=1440 \
ro.zram.periodic_wb_delay_hours=24 

# Fingerprint
PRODUCT_PROPERTY_OVERRIDES += \
    ro.vendor.fingerprint.type=udfps_optical \
    ro.vendor.fingerprint.sensor_location=540|2109|93
